ROSTER=[
('dragons','Basilisk_Crownless','eightleg','Low wingless eight-legged basilisk; broad shovel skull and serrated tail.'),
('dragons','Ossuary_Kite','kite','Two-legged narrow-chested pterosaur; elongated beak and swept single wing pair.'),
('dragons','Sable_Corkscrew','coil','Limbless S-curved wyrm with lateral neck fins and forked facial barbels.'),
('dragons','Marrow_Hammerhead','hammer','Wide hammerhead skull, four squat legs and short thick paddle wings.'),
('dragons','Gale_Triptych','sixwing','Slender two-legged dragon with three independently articulated wing pairs.'),
('dragons','Ashen_Tortoise','shell','Wingless quadrupedal shield-backed dragon; low head and interlocking shell segments.'),
('dragons','Crescent_Manta','manta','Flattened ray-like gliding dragon, no walking legs; split crescent tail.'),
('dragons','Ivory_Ramwyrm','ram','Upright two-legged muscular wyrm; curved ram horns and vestigial sail wings.'),
('dragons','Glass_Needle','needle','Tall stilt-legged dragon with long upright neck, needle beak and four narrow wings.'),
('dragons','Brine_Sawback','flipper','Aquatic crocodilian dragon with six paddles, saw-edged back and broad swimming tail.'),
('bosses','Harbour_Dredger','dredger','Three-legged industrial excavator, offset cockpit, cable winch and unequal pincer arms.'),
('bosses','Vector_Widow','widow','Six-legged radial machine; central optical mast and blade-shaped articulated leg guards.'),
('bosses','Pendulum_Judge','judge','Very tall narrow humanoid, suspended ring head, hanging robe and asymmetric chain arm.'),
('bosses','Gorgon_Priest','gorgon','Four-armed snake-bodied priest with flared hood and fanged face.'),
('bosses','Carrion_Choir','choir','Four-legged birdlike torso with three individually articulated beaked necks.'),
('bosses','Molten_Ram','furnace','Broad quadrupedal furnace machine with rear exhausts, ram shield and splayed industrial feet.'),
('bosses','Tidal_Censer','jelly','Suspended layered bell mantle with eight long independently rigged tentacles.'),
('bosses','Gravetusk','mole','Low six-legged burrower, broad digging hands, plated back and paired forward tusks.'),
('bosses','Rift_Oracle','oracle','Floating angular torso, one masked head and six radial articulated blade arms.'),
('bosses','Iron_Executioner','executioner','Forward-leaning humanoid machine, wedge helmet, open waist frame and an integrated cleaver arm.'),
('enemies','Latch_Leech','leech','Limbless tapering segmented worm with circular sucker jaws and backward hooks.'),
('enemies','Needle_Tick','tick','Four-legged tick with flattened oval abdomen and a long needle proboscis.'),
('enemies','Rag_Pilgrim','pilgrim','Stooped thin humanoid with enclosed hood, torn hanging mantle and long fingered hands.'),
('enemies','Cable_Eel','eel','Jointed mechanical eel with exposed spine cables, fin struts and forward sensor.'),
('enemies','Pollen_Moth','moth','Six-legged insect with four broad veined wings, antennae and large separate abdomen.'),
('enemies','Bone_Grazer','grazer','Four-legged grazer with upright short torso, two grasping arms and split plough jaw.'),
('enemies','Ratchet_Rook','rook','Mechanical walking bird with hooked beak, backwards knees and folded narrow wings.'),
('enemies','Quarry_Slug','slug','Limbless thick slug with asymmetric stepped mineral shell and two eyestalks.'),
('enemies','Lantern_Toad','toad','Squat four-legged amphibian with wide jaw, expanded throat sac and splayed digits.'),
('enemies','Reef_Anemone','anemone','Stationary rooted creature with twelve crown tentacles and a radial feeding mouth.')]
